---
- name: Update apt
  become: true
  apt:
    update_cache: yes
- name: Upgrade packages
  become: true
  apt:
    upgrade: full
- name: Install required packages
  become: true
  apt:
    name:
      - acl
      - ca-certificates
      - curl
      - git
      - htop
      - iotop
      - links
      - logrotate
      - lsb-release
      - multitail
      - nano
      - neovim
      - nginx
      - pipx
      - python-is-python3
      - python3
      - python3-apt
      - python3-pexpect
      - python3-pip
      - python3-venv
      - rsync
      - screen
      - sudo
      - unzip
      - wget
      - zip
    state: present
- name: Install uv
  become: true
  pip:
    name: uv
    break_system_packages: true
- name: Locales configuration, generated locales
  become: true
  lineinfile:
    dest: /etc/locale.gen
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: "^#? fr_FR.UTF-8 UTF-8", line: "fr_FR.UTF-8 UTF-8", state: present }
- name: Locales configuration, default locale
  become: true
  debconf:
    name: locales
    question: locales/default_environment_locale
    value: fr_FR.UTF-8 UTF-8
    vtype: select
  notify: Rebuild locales database
- name: Create project dirs to project repo
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: redadeg
    group: redadeg
  loop:
    - /data
    - /data/projets
- name: Clone the project repo
  git:
    repo: https://github.com/osm-bzh/ar_redadeg.git
    dest: /data/ar_redadeg
- name: Create a venv for the project and install packages
  moreati.uv.pip:
    name: setuptools,psycopg2-binary,wget
    virtualenv: /data/ar_redadeg/.venv
- import_tasks: nginx.yaml
