

- name: install locales package
  apt:
    pkg:
      - locales

- name: configure locales
  lineinfile:
    dest: /etc/locale.gen
    regexp: "{{ item }}"
    line: "{{ item }}"
  notify:
    - generate locales
  with_items:
    - en_GB.UTF-8 UTF-8
    - en_US.UTF-8 UTF-8
    - fr_FR.UTF-8 UTF-8
  when: ansible_distribution == 'Debian'


- name: create locales
  copy:
    content: ""
    dest: /var/lib/locales/supported.d/local
    force: no
    owner: root
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

- name: configure locales
  lineinfile:
    dest: /var/lib/locales/supported.d/local
    regexp: "{{ item }}"
    line: "{{ item }}"
  notify:
    - generate locales
  with_items:
    - en_GB.UTF-8 UTF-8
    - en_US.UTF-8 UTF-8
    - fr_FR.UTF-8 UTF-8
  when: ansible_distribution == 'Ubuntu'

- name: select default locale
  debconf:
    name: locales
    question: locales/default_environment_locale
    value: fr_FR.UTF-8 UTF-8
    vtype: select
  notify:
    - generate locales

