---
- name: Install required packages
  become: true
  apt:
    name: gdal-bin,osm2pgsql,osmctools,python3-dev,python-is-python3,openjdk-11-jdk
    state: present
    update_cache: yes
# -----------------------
# Tomcat9 manually
- name: Create tomcat9 dir
  file:
    path: /data/projects/tomcat9
    state: directory
    owner: redadeg
    group: redadeg
- name: tomcat user and group
  become: true
  user:
    name: tomcat
    group: tomcat
    uid: 988
    home: /var/lib/tomcat
    shell: /usr/sbin/nologin
- name: Download tomcat9
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.98/bin/apache-tomcat-9.0.98.tar.gz
    dest: /data/projects/tomcat9/
    checksum: sha512:07d87286e8ee84bb291069c596cf36233e56a14e3ecb6d65eea0fa7c7042ce5e75f5db31f210b96b6b25b80b34e626dd26c5a6ed5c052384a8587d62658b5e16
- name: Create /opt/tomcat dir
  become: true
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
- name: Unzip tomcat9
  become: true
  unarchive:
    src: /data/projects/tomcat9/apache-tomcat-9.0.98.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    owner: tomcat
    group: tomcat
- name: Symlink latest tomcat
  become: true
  file:
    src: /opt/tomcat/apache-tomcat-9.0.98/
    dest: /opt/tomcat/latest
    state: link
    owner: tomcat
    group: tomcat
- name: Copy service file
  become: true
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
- name: Reload systemd, enable and start tomcatt
  become: true
  systemd_service:
    name: tomcat.service
    daemon_reload: true
    enabled: true
    state: restarted
# -----------------------
# Geoserver
- name: Create geoserver dir
  file:
    path: /data/projects/geoserver
    state: directory
    owner: redadeg
    group: redadeg
- name: Download Geoserver source
  get_url:
    url: https://sourceforge.net/projects/geoserver/files/GeoServer/2.26.1/geoserver-2.26.1-war.zip
    dest: /data/projects/geoserver/geoserver-2.26.1.zip
    checksum: sha256:5af0fdcaac1e27ca367638ee6c33aa68ad5a3c13b961bb5761b402566423cb98
- name: Unzip Geoserver source
  unarchive:
    src: /data/projects/geoserver/geoserver-2.26.1.zip
    dest: /data/projects/geoserver/
    remote_src: yes
- name: Symlink geoserver.war to webapps
  become: true
  file:
    src: /data/projects/geoserver/geoserver.war
    dest: /opt/tomcat/latest/webapps/geoserver.war
    state: link
- name: Restart tomcat9 
  become: true
  systemd_service:
    name: tomcat.service
    state: restarted
# -----------------------
# mviewer
- name: Clone mviewer repo
  git:
    repo: https://github.com/mviewer/mviewer.git
    dest: /data/projets/mviewer
- name: Symlink for mviewer config
  file:
    src: /data/projets/ar_redadeg/data/2024/mviewer/kartenn_kontroll.xml
    dest: /data/projets/mviewer/apps/ar-redadeg-2024
    state: link
