---
- include_vars: vault.yaml
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: redadeg
    group: redadeg
  loop:
    - "/data/{{ millesime }}"
    - "/data/{{ millesime }}/backup"
- name: Be sure that postgresql is installed
  become: true
  apt:
    name: postgresql-postgis
    state: present
- name: Change postgres local authentication
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/16/main/pg_hba.conf
    contype: local
    users: all
    databases: all
    method: scram-sha-256
    address: ""
    netmask: ""
- name: Activate and enable postgresql
  become: true
  systemd_service:
    name: postgresql.service
    enabled: true
    state: restarted
# -----------------------
# Postgresql role
- name: Create postgres role
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: "SUPERUSER,CREATEDB,NOCREATEROLE,NOINHERIT,LOGIN,NOREPLICATION,NOBYPASSRLS"
    state: present
