---
- name: Update apt
  become: true
  apt:
    update_cache: yes
- name: Upgrade packages
  become: true
  apt:
    upgrade: full
- name: Install required packages
  become: true
  apt:
    name: curl,pipx,sudo,unzip,git,neovim,nginx,acl
    state: present
- name: Install uv
  become: true
  pip:
    name: uv
    break_system_packages: true
- name: Clone the project repo
  become: true
  git:
    repo: https://github.com/osm-bzh/ar_redadeg.git
    dest: /data/projets/ar_redadeg
- name: Set owner to project repo
  become: true
  file:
    path: /data/projets/ar_redadeg
    state: directory
    owner: redadeg
    group: redadeg
- name: Create a venv for the project and install packages
  moreati.uv.pip:
    name: setuptools,psycopg2-binary,wget
    virtualenv: /data/projets/ar_redadeg/.venv
- name: Start and enable nginx
  become: true
  systemd_service:
    name: nginx
    state: started
    enabled: true
- name: Copy nginx config
  become: true
  copy:
    src: redadeg.conf
    dest: /etc/nginx/sites-available/redadeg.conf
- name: Enable redadeg config in nginx
  become: true
  file:
    src: /etc/nginx/sites-available/redadeg.conf
    dest: /etc/nginx/sites-enabled/redadeg.conf
    state: link
- name: Reload nginx
  become: true
  shell: nginx -t && nginx -s reload
