---
- name: Update apt
  become: true
  apt:
    update_cache: yes
- name: Upgrade packages
  become: true
  apt:
    upgrade: full
- name: Install required packages
  become: true
  apt:
    name: curl,pipx,sudo,unzip
    state: present
- name: Install uv
  become: true
  pip:
    name: uv
    break_system_packages: true
- name: Create the project repo
  become: true
  file:
    path: /data/projects/ar_redadeg
    state: directory
    owner: redadeg
    group: redadeg
- name: Create a venv for the project and install packages
  moreati.uv.pip:
    name: setuptools,psycopg2-binary
    virtualenv: /data/projects/ar_redadeg/.venv


