---
- include_vars: vault.yaml
- name: Add sources to be able to install openjdk-11-jdk
  become: true
  lineinfile:
    path: /etc/apt/sources.list
    line: "deb http://deb.debian.org/debian unstable main non-free contrib"
    state: present
- name: Update apt preferences
  become: true
  copy:
    src: prefer-stable.pref
    dest: /etc/apt/preferences.d/prefer-stable.pref
- name: Install required packages
  become: true
  apt:
    name: gdal-bin,osm2pgsql,osmctools,python3-dev,python-is-python3,openjdk-11-jdk
    state: present
    update_cache: yes
# -----------------------
# Tomcat9 manually
- name: Create tomcat9 dir
  file:
    path: /data/projets/tomcat9
    state: directory
    owner: redadeg
    group: redadeg
- name: Create a tomcat group
  become: true
  group:
    name: tomcat
    state: present
- name: Create a tomcat user
  become: true
  user:
    name: tomcat
    group: tomcat
    uid: 988
    home: /var/lib/tomcat
    shell: /usr/sbin/nologin
- name: Download tomcat9
  get_url:
    url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /data/projets/tomcat9/
    checksum: "sha512:{{ tomcat_sha512 }}"
- name: Create /opt/tomcat dir
  become: true
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
- name: Unzip tomcat9
  become: true
  unarchive:
    src: "/data/projets/tomcat9/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /opt/tomcat
    remote_src: yes
    owner: tomcat
    group: tomcat
- name: Symlink latest tomcat
  become: true
  file:
    src: "/opt/tomcat/apache-tomcat-{{ tomcat_version }}/"
    dest: /opt/tomcat/latest
    state: link
    owner: tomcat
    group: tomcat
- name: Copy service file
  become: true
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
- name: Reload systemd, enable and start tomcat
  become: true
  systemd_service:
    name: tomcat.service
    daemon_reload: true
    enabled: true
    state: restarted
# -----------------------
# Geoserver
- name: Create geoserver dir
  file:
    path: /data/projets/geoserver
    state: directory
    owner: redadeg
    group: redadeg
- name: Download Geoserver source
  get_url:
    url: https://sourceforge.net/projects/geoserver/files/GeoServer/2.26.1/geoserver-2.26.1-war.zip
    dest: /data/projets/geoserver/geoserver-2.26.1.zip
    checksum: sha256:5af0fdcaac1e27ca367638ee6c33aa68ad5a3c13b961bb5761b402566423cb98
- name: Unzip Geoserver source
  unarchive:
    src: /data/projets/geoserver/geoserver-2.26.1.zip
    dest: /data/projets/geoserver/
    remote_src: yes
- name: Symlink geoserver.war to webapps
  become: true
  file:
    src: /data/projets/geoserver/geoserver.war
    dest: /opt/tomcat/latest/webapps/geoserver.war
    state: link
- name: Copy Geoserver config
  become: true
  template:
    src: web.xml.j2
    dest: /opt/tomcat/latest/webapps/geoserver/WEB-INF/web.xml
- name: Restart tomcat9 
  become: true
  systemd_service:
    name: tomcat.service
    state: restarted
# -----------------------
# mviewer
- name: Clone mviewer repo
  git:
    repo: https://github.com/mviewer/mviewer.git
    dest: /data/projets/mviewer
- name: Symlink for mviewer config
  file:
    src: /data/ar_redadeg/data/2024/mviewer/kartenn_kontroll.xml
    dest: /data/projets/mviewer/apps/ar-redadeg-2024
    state: link
